tasks:
  - init: npm install && npm install -g eslint
  - command: npm run start:dev && npx pm2 monit
ports:
  - port: 8080
    onOpen: open-preview
vscode:
  extensions:
    - dbaeumer.vscode-eslint@2.1.8:02aHhbJ0Q4aGdjHXlTdVKg==