image: gitpod/workspace-full

tasks:
  - init: npm install && npm install -g eslint
  - command: npm run start:dev-watch
    name: Start PM2

ports:
  - port: 8080

vscode:
  extensions:
    - dbaeumer.vscode-eslint@2.1.8:02aHhbJ0Q4aGdjHXlTdVKg==